id: I7A2B6A06
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T20:57:32+00:00'
last_modified: '2022-06-08T17:25:02.501351+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25527
  title: སེམས་གཏམ་རྩོམ་སྒྲིག་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    35C7:
      image_group_id: I1KG25529
      title: ''
      total_pages: 214
      order: 1
      base_file: 35C7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
