id: P010772
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-20 10:23:49.736795
source_metadata:
  id: bdr:W1KG25527
  title: སེམས་གཏམ་རྩོམ་སྒྲིག་པ།
  author: ''
  volumes:
    2bb954c8bd444506a62bf134a6caf328:
      image_group_id: I1KG25529
      title: ''
      volume_number: 1
      total_pages: 214
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
